# This is a basic workflow to help you get started with Actions

name: "Green Main"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          xcodebuild -project PhotoPlenka.xcodeproj \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED="NO" \
            CODE_SIGN_ENTITLEMENTS=""\
            CODE_SIGNING_ALLOWED="NO"

